<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Creating a Corpus – Text Analysis with R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-4622d65869db0eb0c1673d809f0e76d8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="_static/css/styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-CreatingACorpus.html">2. Creating a Corpus</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto"><div class="quarto-sidebar-header"><div class="sidebar-header-item">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="_static/images/analytics.png" class="img-fluid figure-img"></p>
<figcaption><a href="https://www.flaticon.com/free-icons/report" title="report icons" target="_blank" class="header-icon-attribution">Report icons created by Freepik - Flaticon</a></figcaption>
</figure>
</div>
</div></div>
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Text Analysis with R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/jairomelo/text-analysis-workshop" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summary and Setup</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-basicConcepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Basic Concepts</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-CreatingACorpus.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">2. Creating a Corpus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-basicTextAnalysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Basic Text Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-TF-IDF.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. TF-IDF Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-findingSimilarities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Finding Similarities</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#preprocessing-steps" id="toc-preprocessing-steps" class="nav-link active" data-scroll-target="#preprocessing-steps">Preprocessing Steps</a></li>
  <li><a href="#create-a-corpus" id="toc-create-a-corpus" class="nav-link" data-scroll-target="#create-a-corpus">Create a Corpus</a>
  <ul class="collapse">
  <li><a href="#fetch-the-texts" id="toc-fetch-the-texts" class="nav-link" data-scroll-target="#fetch-the-texts">Fetch the Texts</a></li>
  <li><a href="#cleaning" id="toc-cleaning" class="nav-link" data-scroll-target="#cleaning">Cleaning</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Creating a Corpus</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this episode, we’re going to create a corpus of texts and prepare it for analysis by performing some standard preprocessing. Because of the nature of R, we will be transforming plain text files into tibbles, which are a modern take on data frames that make data manipulation easier and more intuitive.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Why not bags of words?">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why not bags of words?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If you’re coming from Python, your instinct might be to create lists (like numpy arrays) for text analysis. But R’s strength lies in structured data frames. By using tibbles instead of simple word lists, we can preserve text relationships and leverage the full tidyverse ecosystem.</p>
</div>
</div>
</div>
<p>To better understand what happens when we process a series of books, let’s start with an exercise using Kafka’s short story “Before the Law.”</p>
<p>First, we need to install and load the <code>tidyverse</code> package, which includes <code>dplyr</code>, <code>ggplot2</code>, and other useful packages for data manipulation and visualization.</p>
<p>In RStudio, create a new R script (File → New File → R Script) and write the following commands. You can execute each line by placing your cursor on it and pressing Ctrl+Enter:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we’ll create a text variable that stores our short story. We’re using <code>tryCatch()</code> to handle any potential errors when reading the file, and the <code>read_lines()</code> function, which is part of the <code>readr</code> package, to read the text file line by line safely.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>beforethelaw_url <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/jairomelo/text-analysis-workshop/refs/heads/main/episodes/texts/Kafka-beforethelaw.txt"</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>beforethelaw <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>(</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">read_lines</span>(beforethelaw_url, <span class="at">locale =</span> <span class="fu">locale</span>(<span class="at">encoding =</span> <span class="st">"UTF-8"</span>)),</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">error =</span> <span class="cf">function</span>(e) {</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">message</span>(<span class="st">"Error reading the text: "</span>, e)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>        <span class="fu">return</span>(<span class="cn">NULL</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>beforethelaw</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "BEFORE THE LAW"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
[2] ""                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
[3] "Before the law sits a gatekeeper. To this gatekeeper comes a man from the country who asks to gain entry into the law. But the gatekeeper says that he cannot grant him entry at the moment. The man thinks about it and then asks if he will be allowed to come in sometime later on. “It is possible,” says the gatekeeper, “but not now.” The gate to the law stands open, as always, and the gatekeeper walks to the side, so the man bends over in order to see through the gate into the inside. When the gatekeeper notices that, he laughs and says: “If it tempts you so much, try going inside in spite of my prohibition. But take note. I am powerful. And I am only the lowliest gatekeeper. But from room to room stand gatekeepers, each more powerful than the last. I cannot endure even one glimpse of the third.” The man from the country has not expected such difficulties: the law should always be accessible for everyone, he thinks, but as he now looks more closely at the gatekeeper in his fur coat, at his large pointed nose and his long, thin, black Tartar’s beard, he decides that it would be better to wait until he gets permission to go inside. The gatekeeper gives him a stool and allows him to sit down at the side in front of the gate. There he sits for days and years. He makes many attempts to be let in, and he wears the gatekeeper out with his requests. The gatekeeper often interrogates him briefly, questioning him about his homeland and many other things, but they are indifferent questions, the kind great men put, and at the end he always tells him once more that he cannot let him inside yet. The man, who has equipped himself with many things for his journey, spends everything, no matter how valuable, to win over the gatekeeper. The latter takes it all but, as he does so, says, “I am taking this only so that you do not think you have failed to do anything.” During the many years the man observes the gatekeeper almost continuously. He forgets the other gatekeepers, and this first one seems to him the only obstacle for entry into the law. He curses the unlucky circumstance, in the first years thoughtlessly and out loud; later, as he grows old, he only mumbles to himself. He becomes childish and, since in the long years studying the gatekeeper he has also come to know the fleas in his fur collar, he even asks the fleas to help him persuade the gatekeeper. Finally his eyesight grows weak, and he does not know whether things are really darker around him or whether his eyes are merely deceiving him. But he recognizes now in the darkness an illumination which breaks inextinguishably out of the gateway to the law. Now he no longer has much time to live. Before his death he gathers up in his head all his experiences of the entire time into one question which he has not yet put to the gatekeeper. He waves to him, since he can no longer lift up his stiffening body. The gatekeeper has to bend way down to him, for the difference between them has changed considerably to the disadvantage of the man. “What do you want to know now?” asks the gatekeeper. “You are insatiable.” “Everyone strives after the law,” says the man, “so how is it that in these many years no one except me has requested entry?” The gatekeeper sees that the man is already dying and, in order to reach his diminishing sense of hearing, he shouts at him, “Here no one else can gain entry, since this entrance was assigned only to you. I’m going now to close it.”"</code></pre>
</div>
</div>
<p>Now that we have our text stored as a character vector, we can transform it into a tibble. This process includes removing the title and filtering out empty lines.</p>
<p>To remove the title, we can use the <code>str_remove_all()</code> function from the <code>stringr</code> package. Our approach in this case is very direct, as we are matching the exact title line.</p>
<p>To remove the empty lines we can use the <code>filter()</code> function from <code>dplyr</code> to match non-empty strings.</p>
<p>Finally, because we’re transforming the character vector into a tibble, it’s important to add an ID column to preserve the original line order and uniquely identify each line.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>beforethelaw <span class="ot">&lt;-</span> beforethelaw <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_remove_all</span>(<span class="st">"^BEFORE THE LAW$"</span>) <span class="co"># Remove the exact title line (^ = start, $ = end)</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>beforethelaw_tibble <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">text =</span> beforethelaw) <span class="sc">%&gt;%</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(text <span class="sc">!=</span> <span class="st">""</span>) <span class="sc">%&gt;%</span> <span class="co"># Remove empty lines</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">id =</span> <span class="fu">row_number</span>()) <span class="co"># Add an ID column to preserve line order</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>beforethelaw_tibble</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  text                                                                        id
  &lt;chr&gt;                                                                    &lt;int&gt;
1 Before the law sits a gatekeeper. To this gatekeeper comes a man from t…     1</code></pre>
</div>
</div>
<p>The result is a two-column tibble: one for the text and another for the line ID.</p>
<p>Now, we can proceed to perform some preprocessing steps to prepare our text for analysis. This includes converting the text to lowercase, removing punctuation, and tokenizing the text into individual words.</p>
<section id="preprocessing-steps" class="level2">
<h2 class="anchored" data-anchor-id="preprocessing-steps">Preprocessing Steps</h2>
<p>Although a text can be analyzed in its raw form, preprocessing is essential for improving the quality of the analysis. Here are the key steps we’ll perform:</p>
<ol type="1">
<li><strong>Convert to Lowercase</strong>: This helps to standardize the text and avoid treating the same words with different cases as distinct.</li>
<li><strong>Remove Punctuation</strong>: Punctuation marks can interfere with text analysis (e.g., “gatekeeper.” would be considered different from “gatekeeper”), so we’ll remove them.</li>
<li><strong>Tokenization</strong>: This is the process of splitting the text into individual words or tokens, which is crucial for most text analysis tasks.</li>
</ol>
<p>Let’s implement these preprocessing steps using <code>dplyr</code>, <code>stringr</code>, and <code>tidytext</code>. This approach allows us to chain multiple operations together:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidytext) <span class="co"># We'll need this for tokenization</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>beforethelaw_preprocessed <span class="ot">&lt;-</span> beforethelaw_tibble <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">text =</span> <span class="fu">str_to_lower</span>(text)) <span class="sc">%&gt;%</span>        <span class="co"># Convert to lowercase</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">text =</span> <span class="fu">str_remove_all</span>(text, <span class="st">"[[:punct:]]"</span>)) <span class="sc">%&gt;%</span>  <span class="co"># Remove punctuation</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">unnest_tokens</span>(word, text)                    <span class="co"># Tokenization into individual words</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>beforethelaw_preprocessed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 640 × 2
      id word      
   &lt;int&gt; &lt;chr&gt;     
 1     1 before    
 2     1 the       
 3     1 law       
 4     1 sits      
 5     1 a         
 6     1 gatekeeper
 7     1 to        
 8     1 this      
 9     1 gatekeeper
10     1 comes     
# ℹ 630 more rows</code></pre>
</div>
</div>
<p>We’ve transformed our single-row tibble into a long 640-row tibble, where each row represents a single word from the original text. The <code>unnest_tokens()</code> function from the <code>tidytext</code> package is particularly useful here, as it automatically handles tokenization and creates a new row for each word.</p>
<p>Note that this number of rows matches the word count from the previous episode. However, this alignment won’t always occur. Depending on text complexity, basic word counting and tokenization can produce different results. For example, tokenization might split contractions (“don’t” → “don” + “t”) or treat hyphenated words (“twenty-one”) as separate tokens, while a simple word count would treat them as single units.</p>
<p>Depending on the purposes of your analysis, you may want to perform additional preprocessing steps, such as removing stop words (common words like “the,” “and,” “is” that may not carry significant meaning for analysis). Let’s remove stop words for this example using the <code>tidytext</code> package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>beforethelaw_reduced <span class="ot">&lt;-</span> beforethelaw_preprocessed <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">anti_join</span>(stop_words, <span class="at">by =</span> <span class="st">"word"</span>) <span class="co"># anti_join removes words that match the stop_words list</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>beforethelaw_reduced</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 164 × 2
      id word      
   &lt;int&gt; &lt;chr&gt;     
 1     1 law       
 2     1 sits      
 3     1 gatekeeper
 4     1 gatekeeper
 5     1 country   
 6     1 gain      
 7     1 entry     
 8     1 law       
 9     1 gatekeeper
10     1 grant     
# ℹ 154 more rows</code></pre>
</div>
</div>
<p>This new tibble has 164 rows, meaning we’ve reduced our original text by 75% by removing stop words. This is important to keep in mind, as preprocessing can improve analysis quality by reducing noise and focusing on relevant terms, but it can also result in a loss of context or meaning that may be important for certain types of analysis.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Stop word removal isn’t always necessary. For tasks like authorship attribution or sentiment analysis, these “common” words can actually provide valuable information about writing style or tone.</p>
</div>
</div>
</section>
<section id="create-a-corpus" class="level2">
<h2 class="anchored" data-anchor-id="create-a-corpus">Create a Corpus</h2>
<p>The term “corpus” is borrowed from Latin. The main meaning of that word is “body,” but in medieval Latin, a collection of writings about the same topic were also called “corpus” (e.g.&nbsp;the “Corpus Juris Civilis”). In text analysis, we use this term more broadly to refer to the entire body of text that we are analyzing, but usually it implies a previous curation of what texts are included so that they share a common theme, time period, or author. Corpora can range from a few documents to millions of texts, depending on the research question.</p>
<p>We’ve curated a corpus of classic works in the public domain. These works share some common themes, styles, and historical contexts, making them suitable for comparative analysis.</p>
<p>We have included 26 works by 20 authors, from a period spanning from 1726 to 1925, although, most works are from the 19th century. We aim to create a corpus useful for demonstration purposes while keeping some consistency in terms of length and genre to allow for meaningful comparisons.</p>
<p>The <code>glID</code> column contains Project Gutenberg identification numbers, which can be used to construct URLs for downloading the full texts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>corpus <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>author, <span class="sc">~</span>title, <span class="sc">~</span>year, <span class="sc">~</span>glID, <span class="sc">~</span>genre,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Jane Austen"</span>, <span class="st">"Pride and Prejudice"</span>, <span class="dv">1813</span>, <span class="dv">1342</span>, <span class="st">"Social Fiction"</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Charles Dickens"</span>, <span class="st">"A Tale of Two Cities"</span>, <span class="dv">1859</span>, <span class="dv">98</span>, <span class="st">"Social Fiction"</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"F. Scott Fitzgerald"</span>, <span class="st">"The Great Gatsby"</span>, <span class="dv">1925</span>, <span class="dv">64317</span>, <span class="st">"Social Fiction"</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Mary Wollstonecraft Shelley"</span>, <span class="st">"Frankenstein; Or, The Modern Prometheus"</span>, <span class="dv">1818</span>, <span class="dv">84</span>, <span class="st">"Gothic"</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Herman Melville"</span>, <span class="st">"Moby Dick"</span>, <span class="dv">1851</span>, <span class="dv">2701</span>, <span class="st">"Adventure"</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Louisa May Alcott"</span>, <span class="st">"Little Women"</span>, <span class="dv">1868</span>, <span class="dv">37106</span>, <span class="st">"Domestic Fiction"</span>,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Mark Twain"</span>, <span class="st">"Tom Sawyer"</span>, <span class="dv">1876</span>, <span class="dv">74</span>, <span class="st">"Adventure"</span>,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Jonathan Swift"</span>, <span class="st">"Gulliver's Travels"</span>, <span class="dv">1726</span>, <span class="dv">17157</span>, <span class="st">"Satirical Fiction"</span>,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"E. M. Forster"</span>, <span class="st">"A Room with a View"</span>, <span class="dv">1908</span>, <span class="dv">2641</span>, <span class="st">"Social Fiction"</span>,</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Elizabeth Von Arnim"</span>, <span class="st">"The Enchanted April"</span>, <span class="dv">1922</span>, <span class="dv">16389</span>, <span class="st">"Social Fiction"</span>,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Lewis Carroll"</span>, <span class="st">"Alice's Adventures in Wonderland"</span>, <span class="dv">1865</span>, <span class="dv">11</span>, <span class="st">"Fantasy"</span>,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Elizabeth Gaskell"</span>, <span class="st">"Cranford"</span>, <span class="dv">1853</span>, <span class="dv">394</span>, <span class="st">"Domestic Fiction"</span>,</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Charles Dickens"</span>, <span class="st">"The Pickwick Papers"</span>, <span class="dv">1836</span>, <span class="dv">580</span>, <span class="st">"Social Fiction"</span>,</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"J. M. Barrie"</span>, <span class="st">"Peter Pan"</span>, <span class="dv">1911</span>, <span class="dv">16</span>, <span class="st">"Fantasy"</span>,</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Charles Dickens"</span>, <span class="st">"Great Expectations"</span>, <span class="dv">1861</span>, <span class="dv">1400</span>, <span class="st">"Social Fiction"</span>,</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Robert Louis Stevenson"</span>, <span class="st">"Treasure Island"</span>, <span class="dv">1883</span>, <span class="dv">120</span>, <span class="st">"Adventure"</span>,</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Kenneth Grahame"</span>, <span class="st">"The Wind in the Willows"</span>, <span class="dv">1908</span>, <span class="dv">27805</span>, <span class="st">"Fantasy"</span>,</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Jules Verne"</span>, <span class="st">"Twenty Thousand Leagues Under the Seas"</span>, <span class="dv">1870</span>, <span class="dv">2488</span>, <span class="st">"Science Fiction"</span>,</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Jules Verne"</span>, <span class="st">"A Journey to the Centre of the Earth"</span>, <span class="dv">1864</span>, <span class="dv">18857</span>, <span class="st">"Science Fiction"</span>,</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Jules Verne"</span>, <span class="st">"Around the World in Eighty Days"</span>, <span class="dv">1873</span>, <span class="dv">103</span>, <span class="st">"Adventure"</span>,</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Bram Stoker"</span>, <span class="st">"Dracula"</span>, <span class="dv">1897</span>, <span class="dv">345</span>, <span class="st">"Gothic"</span>,</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>  <span class="st">"H. G. Wells"</span>, <span class="st">"The Time Machine"</span>, <span class="dv">1895</span>, <span class="dv">35</span>, <span class="st">"Science Fiction"</span>,</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Charlotte Brontë"</span>, <span class="st">"Jane Eyre"</span>, <span class="dv">1847</span>, <span class="dv">1260</span>, <span class="st">"Gothic"</span>,</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Jane Austen"</span>, <span class="st">"Northanger Abbey"</span>, <span class="dv">1817</span>, <span class="dv">121</span>, <span class="st">"Social Fiction"</span>,</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Elizabeth Gaskell"</span>, <span class="st">"North and South"</span>, <span class="dv">1855</span>, <span class="dv">4276</span>, <span class="st">"Social Fiction"</span></span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>corpus</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 25 × 5
   author                      title                            year  glID genre
   &lt;chr&gt;                       &lt;chr&gt;                           &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;
 1 Jane Austen                 Pride and Prejudice              1813  1342 Soci…
 2 Charles Dickens             A Tale of Two Cities             1859    98 Soci…
 3 F. Scott Fitzgerald         The Great Gatsby                 1925 64317 Soci…
 4 Mary Wollstonecraft Shelley Frankenstein; Or, The Modern P…  1818    84 Goth…
 5 Herman Melville             Moby Dick                        1851  2701 Adve…
 6 Louisa May Alcott           Little Women                     1868 37106 Dome…
 7 Mark Twain                  Tom Sawyer                       1876    74 Adve…
 8 Jonathan Swift              Gulliver's Travels               1726 17157 Sati…
 9 E. M. Forster               A Room with a View               1908  2641 Soci…
10 Elizabeth Von Arnim         The Enchanted April              1922 16389 Soci…
# ℹ 15 more rows</code></pre>
</div>
</div>
<p>We can have a glimpse of the corpus by examining how many authors and how many genres are represented.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the corpus</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>corpus <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(author, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 19 × 2
   author                          n
   &lt;chr&gt;                       &lt;int&gt;
 1 Charles Dickens                 3
 2 Jules Verne                     3
 3 Elizabeth Gaskell               2
 4 Jane Austen                     2
 5 Bram Stoker                     1
 6 Charlotte Brontë                1
 7 E. M. Forster                   1
 8 Elizabeth Von Arnim             1
 9 F. Scott Fitzgerald             1
10 H. G. Wells                     1
11 Herman Melville                 1
12 J. M. Barrie                    1
13 Jonathan Swift                  1
14 Kenneth Grahame                 1
15 Lewis Carroll                   1
16 Louisa May Alcott               1
17 Mark Twain                      1
18 Mary Wollstonecraft Shelley     1
19 Robert Louis Stevenson          1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>corpus <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(genre, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
  genre                 n
  &lt;chr&gt;             &lt;int&gt;
1 Social Fiction        9
2 Adventure             4
3 Fantasy               3
4 Gothic                3
5 Science Fiction       3
6 Domestic Fiction      2
7 Satirical Fiction     1</code></pre>
</div>
</div>
<p>We can observe how our corpus contains works by mostly individual authors, although with some exceptions as Dickens, Verne, Gaskell and Austen. In terms of genres, we have a diverse range, with a strong representation of Social Fiction, Adventure, and Fantasy, alongside notable works in Gothic and Science Fiction.</p>
<p>Another relevant point about this corpus is that it represents what became the “standard” English-language literary canon, even with the inclusion of Verne’s works, which were originally written in French but became deeply embedded in English-language reading culture through translation. This corpus is a good starting point for exploring the evolution of English literature and the themes that have persisted over time.</p>
<section id="fetch-the-texts" class="level3">
<h3 class="anchored" data-anchor-id="fetch-the-texts">Fetch the Texts</h3>
<p>Our next step is to fetch the full text that constitutes our corpus. We will use the <code>glID</code> (Gutenberg Library ID) to retrieve the texts from the Project Gutenberg website. To facilitate this process, we can use the <code>gutenbergr</code> package in R, which handles the downloading and cleaning automatically.</p>
<p>Step by step, what we are going to do is install and load the gutenbergr package, which handles the downloading and cleaning automatically (removing Project Gutenberg headers, footers, and formatting markers).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"gutenbergr"</span>) <span class="co"># Install if needed (run once)</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gutenbergr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After that, we need to iterate over the <code>glIDs</code> in our corpus for the package to know what book to download. The function <code>gutenberg_download()</code> will take the <code>glID</code> as an argument and return the full text of the book as a tibble with two columns, like this one:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gutenberg_download</span>(<span class="dv">1342</span>) <span class="co"># 1342 is the ID for "Pride and Prejudice"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Determining mirror for Project Gutenberg from
https://www.gutenberg.org/robot/harvest.
Using mirror http://aleph.gutenberg.org.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 14,527 × 2
   gutenberg_id text                                            
          &lt;int&gt; &lt;chr&gt;                                           
 1         1342 "                             GEORGE ALLEN"     
 2         1342 "                               PUBLISHER"      
 3         1342 ""                                              
 4         1342 "                        156 CHARING CROSS ROAD"
 5         1342 "                                LONDON"        
 6         1342 ""                                              
 7         1342 "                             RUSKIN HOUSE"     
 8         1342 "                                   ]"          
 9         1342 ""                                              
10         1342 "                            [Illustration:"    
# ℹ 14,517 more rows</code></pre>
</div>
</div>
<p>This tibble needs to be transformed into a single text string that fits in a column of our corpus tibble. We can use the <code>pull()</code> function to extract the text column and then use <code>paste(collapse = " ")</code> to concatenate all the lines into a single string.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Download all books at once</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>corpus_texts <span class="ot">&lt;-</span> corpus <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(<span class="at">text =</span> <span class="fu">map</span>(glID, <span class="sc">~</span><span class="fu">gutenberg_download</span>(.x) <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>   <span class="fu">pull</span>(text) <span class="sc">%&gt;%</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">paste</span>(<span class="at">collapse =</span> <span class="st">" "</span>)))</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>corpus_texts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 25 × 6
   author                      title                      year  glID genre text 
   &lt;chr&gt;                       &lt;chr&gt;                     &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;lis&gt;
 1 Jane Austen                 Pride and Prejudice        1813  1342 Soci… &lt;chr&gt;
 2 Charles Dickens             A Tale of Two Cities       1859    98 Soci… &lt;chr&gt;
 3 F. Scott Fitzgerald         The Great Gatsby           1925 64317 Soci… &lt;chr&gt;
 4 Mary Wollstonecraft Shelley Frankenstein; Or, The Mo…  1818    84 Goth… &lt;chr&gt;
 5 Herman Melville             Moby Dick                  1851  2701 Adve… &lt;chr&gt;
 6 Louisa May Alcott           Little Women               1868 37106 Dome… &lt;chr&gt;
 7 Mark Twain                  Tom Sawyer                 1876    74 Adve… &lt;chr&gt;
 8 Jonathan Swift              Gulliver's Travels         1726 17157 Sati… &lt;chr&gt;
 9 E. M. Forster               A Room with a View         1908  2641 Soci… &lt;chr&gt;
10 Elizabeth Von Arnim         The Enchanted April        1922 16389 Soci… &lt;chr&gt;
# ℹ 15 more rows</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Understanding the `map()` function">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Understanding the <code>map()</code> function
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The <code>map()</code> function from the <code>purrr</code> package (part of tidyverse) applies a function to each element of a vector or list. In our case:</p>
<ul>
<li><code>map(glID, ~...)</code> takes each ID from the glID column</li>
<li>The <code>~</code> creates an anonymous function (similar to a lambda function in Python)</li>
<li><code>.x</code> represents each individual ID as <code>map()</code> processes them one by one</li>
<li>So <code>~gutenberg_download(.x)</code> means “for each ID, download that book”</li>
</ul>
<p>This is equivalent to writing a for loop, but more concise and functional programming style. The result is that each book gets downloaded and processed, creating a new <code>text</code> column in our tibble.</p>
<p>If you’re new to <code>map()</code>, think of it as “do this same operation to every item in this list.”</p>
</div>
</div>
</div>
<p>In the end, we will have a <code>corpus_texts</code> tibble that contains the full text of each book in our corpus as a character vector stored in the <code>text</code> column.</p>
</section>
<section id="cleaning" class="level3">
<h3 class="anchored" data-anchor-id="cleaning">Cleaning</h3>
<p>The texts provided by the Gutenberg Library are almost ready for analysis. However, we still need to perform some basic cleaning steps to ensure consistency and remove any unwanted artifacts.</p>
<section id="understanding-preprocessing-decisions" class="level4">
<h4 class="anchored" data-anchor-id="understanding-preprocessing-decisions">Understanding Preprocessing Decisions</h4>
<p>Before applying cleaning steps mechanically, it’s important to understand how our preprocessing choices affect the results. A common challenge is handling possessive forms properly.</p>
<p>When we remove all punctuation indiscriminately, we transform possessive forms in ways that might not be intended:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example text to demonstrate the issue</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>example_text <span class="ot">&lt;-</span> <span class="st">"Beth's book and Joe's pen were left at Mary's house."</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Method 1: Remove all punctuation (problematic)</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>simple_clean <span class="ot">&lt;-</span> example_text <span class="sc">%&gt;%</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_to_lower</span>() <span class="sc">%&gt;%</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_remove_all</span>(<span class="st">"[[:punct:]]"</span>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Original:"</span>, example_text, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Original: Beth's book and Joe's pen were left at Mary's house. </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Simple cleaning:"</span>, simple_clean, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple cleaning: beths book and joes pen were left at marys house </code></pre>
</div>
</div>
<p>The simple approach transforms “Beth’s” into “beths”, “Joe’s” into “joes”, etc. We can handle this more elegantly during tokenization by removing the possessive suffix after we’ve split the text into words.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Preprocessing Philosophy">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Preprocessing Philosophy
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Every preprocessing decision shapes your results.</strong> Always consider: - What linguistic information do you want to preserve? - How will your choices affect downstream analysis? - Can you make your preprocessing decisions explicit and reversible?</p>
<p>For possessives, we have several options: - <strong>Remove ‘s suffix<strong>: “Mary’s” → “Mary” (treats possessive as just a reference to the person/thing) - </strong>Expand to ’has’</strong>: “Mary’s book” → “Mary has book” (preserves relationship)<br>
- <strong>Keep as-is</strong>: Preserve the grammatical information</p>
<p>For most text analysis tasks, removing the suffix is the most practical approach.</p>
</div>
</div>
</section>
<section id="applying-smart-cleaning" class="level4">
<h4 class="anchored" data-anchor-id="applying-smart-cleaning">Applying Smart Cleaning</h4>
<p>Let’s apply a straightforward approach: remove punctuation normally, then handle possessives during tokenization:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cleaning the texts - simple approach</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>corpus_texts <span class="ot">&lt;-</span> corpus_texts <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">text_clean =</span> <span class="fu">str_to_lower</span>(text) <span class="sc">%&gt;%</span>               <span class="co"># Convert to lowercase</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>       <span class="fu">str_remove_all</span>(<span class="st">"'s</span><span class="sc">\\</span><span class="st">b"</span>) <span class="sc">%&gt;%</span>                    <span class="co"># Remove possessive 's from full text</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>       <span class="fu">str_remove_all</span>(<span class="st">"[[:punct:]]"</span>) <span class="sc">%&gt;%</span>              <span class="co"># Remove remaining punctuation</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>       <span class="fu">str_squish</span>()                                    <span class="co"># Remove extra whitespace</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>   )</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>corpus_texts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 25 × 7
   author                      title           year  glID genre text  text_clean
   &lt;chr&gt;                       &lt;chr&gt;          &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;lis&gt; &lt;chr&gt;     
 1 Jane Austen                 Pride and Pre…  1813  1342 Soci… &lt;chr&gt; george al…
 2 Charles Dickens             A Tale of Two…  1859    98 Soci… &lt;chr&gt; a tale of…
 3 F. Scott Fitzgerald         The Great Gat…  1925 64317 Soci… &lt;chr&gt; the great…
 4 Mary Wollstonecraft Shelley Frankenstein;…  1818    84 Goth… &lt;chr&gt; frankenst…
 5 Herman Melville             Moby Dick       1851  2701 Adve… &lt;chr&gt; mobydick …
 6 Louisa May Alcott           Little Women    1868 37106 Dome… &lt;chr&gt; illustrat…
 7 Mark Twain                  Tom Sawyer      1876    74 Adve… &lt;chr&gt; the adven…
 8 Jonathan Swift              Gulliver's Tr…  1726 17157 Sati… &lt;chr&gt; gulliver …
 9 E. M. Forster               A Room with a…  1908  2641 Soci… &lt;chr&gt; illustrat…
10 Elizabeth Von Arnim         The Enchanted…  1922 16389 Soci… &lt;chr&gt; illustrat…
# ℹ 15 more rows</code></pre>
</div>
</div>
<p>This code creates a new column <code>text_clean</code> in our <code>corpus_texts</code> tibble, which contains the cleaned text ready for analysis. The <code>str_squish()</code> function is particularly useful as it removes any leading, trailing, or extra spaces between words, ensuring that our text is tidy and consistent.</p>
<p>These are basic cleaning steps that improve the quality of our text data and reduce noise that might interfere with our analysis. However, even after these steps, and even using a high-quality corpus like Project Gutenberg, we still face some challenges such as table of contents, chapter headers, editorial notes, and translator introductions.</p>
<p>In real-world projects, text cleaning often involves both automated processes and manual review to ensure corpus consistency. For our workshop, we’ll assume these texts are clean enough for analysis, but in practice, you may need to spend considerably more time refining your corpus.</p>
<p>Now that we have a clean, standardized corpus of 26 classic works, we’re ready to begin our text analysis journey. In the next section, we’ll start with fundamental techniques: examining word frequencies, calculating lexical density, and measuring readability scores. These basic analyses will give us our first insights into the linguistic patterns that distinguish different authors, genres, and time periods in our corpus.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<div class="footer-left" style="text-align: right; font-size: 0.9em; line-height: 1.5; padding: 1rem 0;">
<p style="margin: 0;">
Created by <strong><a href="https://www.library.ucsb.edu/research-data-services" target="_blank">UCSB Library Research Data Services</a></strong>
</p>
<p style="margin: 0;">
License: <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" style="text-decoration: none; color: #007BFF;">CC BY-NC 4.0</a>
</p>
<p><a href="https://doi.org/10.5281/zenodo.xxxxxxxx" style="display: inline-block; margin-top: 5px;"> <img src="https://zenodo.org/badge/DOI/10.5281/zenodo.xxxxxxxx.svg" alt="DOI" style="border: none;"> </a></p>
</div>
</div>
  </div>
</footer>




</body></html>