project:
  type: website
  output-dir: _site

website: 
  title: "Text Analysis with R"
  page-footer:
    border: false
    background: light
    right: |
        <div class="footer-left" style="text-align: right; font-size: 0.9em; line-height: 1.5; padding: 1rem 0;">
          <p style="margin: 0;">Created by <strong><a href="https://www.library.ucsb.edu/research-data-services" target="_blank">UCSB Library Research Data Services</a></strong></p>
          <p style="margin: 0;">License: <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" style="text-decoration: none; color: #007BFF;">CC BY-NC 4.0</a></p>
          <a href="https://doi.org/10.5281/zenodo.xxxxxxxx" style="display: inline-block; margin-top: 5px;">
            <img src="https://zenodo.org/badge/DOI/10.5281/zenodo.xxxxxxxx.svg" alt="DOI" style="border: none;">
          </a>
        </div>
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        href: https://github.com/jairomelo/text-analysis-workshop
    contents:
      - text: "Summary and Setup"
        href: index.qmd
      - text: "1. Basic Concepts"
        href: 01-basicConcepts.qmd
      - text: "2. Creating a Corpus"
        href: 02-CreatingACorpus.qmd


format:
  html:
    toc: true
    theme: cosmo
    css: static/css/styles.css